version: '3'
services:
  autogpt:
    working_dir: ./vendor/Auto-GPT/autogpts/autogpt
    #volumes:
    #  - ./vendor/Auto-GPT/autogpts/autogpt/benchmark:/benchmark
     # - ./vendor/Auto-GPT-Benchmarks/agbenchmark/:/app/agbenchmark
     # - ./docker-compose.yml:/app/docker-compose.yml
     # - ./vendor/Auto-GPT/autogpts/autogpt/Dockerfile:/app/Dockerfile

    #image: your-autogpt-image:tag
    build:
      #context: vendor/Auto-GPT/
      context: vendor/Auto-GPT/autogpts/autogpt/
    #environment:
      #- GITHUB_PAT="${GITHUB_PAT}"
    # Add other configuration as needed
    depends_on:
      - mockopenai

  mockopenai:
    #image: your-mockopenai-image:tag
    environment:
      - GITHUB_PAT=${GITHUB_PAT}
      - GITHUB_REPO=${GITHUB_REPO}

    build:
      context: vendor/lollms/


