version: '3'
services:

  ai_ticket:
    image: ai_ticket
    build:
      context: .

  autogpt:
    entrypoint: poetry run autogpt --install-plugin-deps --skip-news
    #entrypoint: curl  http://mockopenai:5000/v1
    # uncomment thse next 3 lines for debugging
    #entrypoint: /bin/bash
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
    environment:
      - GITHUB_PAT="${GITHUB_PAT}"
      - GITHUB_REPO="jmikedupont2/ai-ticket"
      - OPENAI_API_KEY=your-openai-api-key
      - OPENAI_API_BASE=http://mockopenai:5000/v1
    build:
      context: vendor/Auto-GPT/
    depends_on:
      - mockopenai

  mockopenai:
    depends_on:
      - ai_ticket

    environment:
      - GITHUB_PAT=${GITHUB_PAT}
      - GITHUB_REPO=${GITHUB_REPO}

    build:
      context: vendor/lollms/
    ports:
      -  "5000:5000"

